name: Bug report
description: Report a bug in the UE nodes 
title: "[Bug]: "
labels: 'Incoming'
assignees: 'chrisgoringe'
body:
- type: markdown
  attributes:
    value: I haven't made any of the fields below mandatory, but the more infomation you give me, the better the chance I will be able to help! |See [this discussion](https://github.com/chrisgoringe/cg-use-everywhere/discussions/294) for more details.

- type: textarea
  id: description
  attributes:
    label: Describe the bug

- type: markdown
  attributes:
    value: "# Versions"

- type: markdown
  attributes:
    value: You can find the ComfyUI and ComfyUI_frontend numbers in Settings -> About, and the Use Everywhere version in Settings -> Use Everywhere.

- type: input
  id: version
  attributes:
    label: ComfyUI version

- type: input
  id: uiversion
  attributes:
    label: ComfyUI_frontend version
    
- type: input
  id: UEversion
  attributes:
    label: Use Everywhere Version
    
- type: input
  id: OS
  attributes:
    label: Operating System and Browser

- type: markdown
  attributes:
    value: "# Javascript Console"
    
- type: markdown
  attributes:
    value: Press f12 on your browser when the bug occurs and see if there is anthing in the console that looks like it might be relevant - copy and paste it here if so.

- type: textarea
  id: console
  attributes:
    label: Javascript Console Log

- type: markdown
  attributes:
    value: "# Anything Else?"
    
- type: markdown
  attributes:
    value: Anything else that might help - screenshots, an example workflow (as simple as possible to illustrate the problem), anything you think might help.

- type: textarea
  id: anythingelse
  attributes:
    label: Anything Else   
